export type LessonSection={id:string;type:string;title:string;summary:string;content:string;bullets?:string[];visualization?:{kind:string;label:string}};
export type QuizQuestion={question:string;options:string[];answer:number;explanation:string};
export const mockLesson={id:'photosynthesis-01',title:'Photosynthesis',overview:'How plants turn light energy into chemical energy — represented through concepts, a process map, comparisons, and examples.',source:'Mock lesson • Biology',sections:[
{id:'overview',type:'concept',title:'What is Photosynthesis?',summary:'The big idea in one view.',content:'Photosynthesis is the process plants use to convert light energy into stored chemical energy. It mainly happens in chloroplasts, using carbon dioxide and water to produce glucose and oxygen.',bullets:['Light energy is captured by chlorophyll.','Carbon dioxide enters from the air.','Water is supplied through the roots.','Glucose stores chemical energy; oxygen is released.'],visualization:{kind:'concept',label:'Concept card'}},
{id:'process',type:'process',title:'How photosynthesis works',summary:'Follow the inputs → transformations → outputs.',content:'Light energy powers a chain of reactions. The visual flow below separates what enters the system, what changes, and what leaves it.',visualization:{kind:'process',label:'Process diagram'}},
{id:'relationships',type:'map',title:'Key relationships',summary:'See how the ideas connect.',content:'Photosynthesis links sunlight, chlorophyll, water, carbon dioxide, glucose, and oxygen into one system.',visualization:{kind:'map',label:'Concept map'}},
{id:'comparison',type:'comparison',title:'Photosynthesis vs. cellular respiration',summary:'Two complementary energy processes.',content:'Photosynthesis stores energy in glucose, while cellular respiration releases usable energy from glucose.',visualization:{kind:'comparison',label:'Comparison'}},
{id:'example',type:'example',title:'A simple real-world example',summary:'Trace one leaf through the system.',content:'On a sunny day, a leaf receives light while roots supply water and pores exchange gases. The plant can then build glucose from the available inputs.',visualization:{kind:'example',label:'Worked example'}},
{id:'chart',type:'chart',title:'Where the inputs go',summary:'A compact visual summary.',content:'The chart is a frontend placeholder for Person 3’s renderer.',visualization:{kind:'chart',label:'Chart placeholder'}}
] as LessonSection[],quiz:[
{question:'Which molecule stores much of the chemical energy produced by photosynthesis?',options:['Glucose','Oxygen','Water','Chlorophyll'],answer:0,explanation:'Glucose is the sugar produced by photosynthesis and stores chemical energy.'},
{question:'What is the main energy input for photosynthesis?',options:['Heat','Light','Oxygen','Glucose'],answer:1,explanation:'Light energy is captured by chlorophyll and drives the photosynthetic reactions.'},
{question:'Which gas is taken in as a carbon source?',options:['Oxygen','Nitrogen','Carbon dioxide','Hydrogen'],answer:2,explanation:'Carbon dioxide provides the carbon used to build glucose.'}
] as QuizQuestion[]};
export function normalizeLesson(input:typeof mockLesson=mockLesson){return {id:input.id,title:input.title,overview:input.overview,source:input.source,sections:input.sections,quiz:input.quiz}}
