"""The steps of making a lesson that do not depend on what it was made from.

Generating, mapping failures onto error codes, wording the notice a reader sees, and revalidating
the finished lesson are identical for a document and for a video. Only ingestion differs, so only
ingestion lives in the per-input services. Both call through here, which is what keeps one
behaviour - one set of error codes, one notice vocabulary, one final validation - across every
input type.
"""

import logging
import time

from pydantic import ValidationError

from app.ai.lesson_assembly import LessonAssemblyError
from app.ai.lesson_generator import AnyLessonRequest, GeneratedLesson, LessonGenerator
from app.ai.provider import (
    AIInputNotSupportedError,
    AIInvalidResponseError,
    AIProviderError,
    AIRateLimitError,
)
from app.core.errors import AppError, ErrorCode
from app.schemas.lesson import Lesson

logger = logging.getLogger(__name__)

INVALID_LESSON = "The AI response could not be turned into a valid lesson. Try again."

# Said the same way whether the mismatch is found when the request is wired up or when a provider
# refuses it, so the reader gets one explanation for one situation.
NO_CAPABLE_PROVIDER = (
    "No AI service that can read this kind of input is available. Video needs a provider that can "
    "watch it; a PDF works with any of them."
)


def elapsed_ms(started: float) -> int:
    return round((time.perf_counter() - started) * 1000)


def demo_notice(material: str) -> str:
    return (
        "Demo mode: AI generation is off or has no API key, so this lesson is fixed example data. "
        f"It does not describe {material}."
    )


def cache_notice(noun: str) -> str:
    return (
        "No AI provider was available. This lesson comes from an earlier successful generation of "
        f"the same {noun}."
    )


def notice_for(generated: GeneratedLesson, *, material: str, noun: str) -> str | None:
    """A plain-language note when the lesson did not come live from the primary provider."""
    if generated.generation_status == "demo":
        return demo_notice(material)
    if generated.generation_status == "cached":
        return cache_notice(noun)
    if generated.generation_status == "fallback":
        return (
            f"The main AI provider was unavailable, so this lesson was generated by "
            f"{generated.provider}."
        )
    return None


async def generate_lesson(generator: LessonGenerator, request: AnyLessonRequest) -> GeneratedLesson:
    """Run generation, turning every expected failure into a client-safe `AppError`.

    Subclasses are caught before their base class, so a rate limit and a capability mismatch are
    never reported as a generic outage.
    """
    started = time.perf_counter()
    try:
        generated = await generator.generate(request)
    except (
        AIRateLimitError,
        AIInvalidResponseError,
        AIInputNotSupportedError,
        AIProviderError,
    ) as exc:
        raise translate_ai_error(exc, request.lesson_id) from exc
    except LessonAssemblyError as exc:
        raise _failed(
            request.lesson_id, exc, ErrorCode.LESSON_VALIDATION_FAILED, INVALID_LESSON
        ) from exc

    logger.info(
        "lesson generated",
        extra={
            "document_id": request.lesson_id,
            "provider": generated.provider,
            "ai_requests": generated.ai_request_count,
            "warning_count": len(generated.warnings),
            "duration_ms": elapsed_ms(started),
        },
    )
    return generated


def translate_ai_error(exc: Exception, lesson_id: str) -> AppError:
    """Map an AI-layer exception onto the `AppError` a client should see.

    Checked before its base class, so a rate limit or a capability mismatch is never reported as a
    generic outage. Shared by `generate_lesson` and by the video upload step in `video_lessons`: a
    Gemini Files API failure while getting a video ready to watch is exactly as much an AI-service
    failure as a model call failing, and deserves the same wording and the same error code.
    """
    if isinstance(exc, AIRateLimitError):
        return _failed(
            lesson_id,
            exc,
            ErrorCode.AI_RATE_LIMITED,
            "The AI service's free-tier limit was reached. Wait a few minutes and try again.",
        )
    if isinstance(exc, AIInvalidResponseError):
        return _failed(
            lesson_id,
            exc,
            ErrorCode.AI_INVALID_RESPONSE,
            "The AI service returned a response that could not be used. Try again.",
        )
    if isinstance(exc, AIInputNotSupportedError):
        return _failed(lesson_id, exc, ErrorCode.AI_INPUT_NOT_SUPPORTED, NO_CAPABLE_PROVIDER)
    return _failed(
        lesson_id,
        exc,
        ErrorCode.AI_PROVIDER_UNAVAILABLE,
        "The AI service is not available right now. Try again later.",
    )


def validate_lesson(lesson: Lesson, document_id: str) -> Lesson:
    """Validate the lesson again from its JSON form, exactly as clients will receive it."""
    started = time.perf_counter()
    try:
        validated = Lesson.model_validate(lesson.model_dump(mode="json", exclude_none=True))
    except ValidationError as exc:
        logger.warning(
            "lesson validation failed",
            extra={"document_id": document_id, "error_count": exc.error_count()},
        )
        raise AppError(ErrorCode.LESSON_VALIDATION_FAILED, INVALID_LESSON) from exc
    logger.info(
        "lesson validated",
        extra={
            "document_id": document_id,
            "validation": "passed",
            "duration_ms": elapsed_ms(started),
        },
    )
    return validated


def _failed(lesson_id: str, exc: Exception, code: ErrorCode, message: str) -> AppError:
    logger.warning(
        "lesson generation failed",
        extra={"document_id": lesson_id, "error_code": code, "reason": str(exc)},
    )
    return AppError(code, message)
