"""Creates lessons from uploaded PDFs: upload -> extract -> chunk -> generate -> validate -> store.

Each step is timed and logged against a document id. Document text and filenames are never logged.
"""

import asyncio
import logging
import time
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path, PurePath
from typing import Self

from fastapi import UploadFile
from pydantic import ValidationError

from app.ai.lesson_assembly import LessonAssemblyError
from app.ai.lesson_generator import GeneratedLesson, LessonGenerationRequest, LessonGenerator
from app.ai.provider import AIInvalidResponseError, AIProviderError, AIRateLimitError
from app.core.config import Settings
from app.core.errors import AppError, ErrorCode
from app.ingestion.pdf import extract_pdf
from app.models.content import ExtractedDocument
from app.schemas.lesson import Lesson, Source
from app.schemas.lessons_api import LessonMetadata, LessonRecord, ProcessingTimings
from app.services.chunking import chunk_document
from app.services.lesson_store import LessonStore
from app.services.uploads import stored_pdf_upload

logger = logging.getLogger(__name__)

MOCK_NOTICE = (
    "Demo mode: AI generation is off or has no API key, so this lesson is fixed example data. "
    "It does not describe the uploaded PDF."
)
CACHE_NOTICE = (
    "No AI provider was available. This lesson comes from an earlier successful generation of the "
    "same document."
)


def _notice_for(generated: GeneratedLesson) -> str | None:
    """A plain-language note when the lesson did not come live from the primary provider."""
    if generated.generation_status == "demo":
        return MOCK_NOTICE
    if generated.generation_status == "cached":
        return CACHE_NOTICE
    if generated.generation_status == "fallback":
        return (
            f"The main AI provider was unavailable, so this lesson was generated by "
            f"{generated.provider}."
        )
    return None


_INVALID_LESSON = "The AI response could not be turned into a valid lesson. Try again."


@dataclass(frozen=True)
class PdfLessonLimits:
    max_upload_mb: int
    max_pages: int
    chunk_max_chars: int


def _elapsed_ms(started: float) -> int:
    return round((time.perf_counter() - started) * 1000)


class PdfLessonService:
    def __init__(
        self,
        *,
        generator: LessonGenerator,
        store: LessonStore,
        uploads_dir: Path,
        limits: PdfLessonLimits,
    ) -> None:
        self._generator = generator
        self._store = store
        self._uploads_dir = uploads_dir
        self._limits = limits

    @classmethod
    def from_settings(
        cls,
        settings: Settings,
        *,
        generator: LessonGenerator,
        store: LessonStore,
    ) -> Self:
        return cls(
            generator=generator,
            store=store,
            uploads_dir=settings.data_dir / "uploads",
            limits=PdfLessonLimits(
                max_upload_mb=settings.max_upload_mb,
                max_pages=settings.pdf_max_pages,
                chunk_max_chars=settings.chunk_max_chars,
            ),
        )

    async def create_lesson(self, upload: UploadFile) -> LessonRecord:
        started = time.perf_counter()
        async with stored_pdf_upload(
            upload, directory=self._uploads_dir, max_mb=self._limits.max_upload_mb
        ) as stored:
            document_id = stored.upload_id
            logger.info(
                "pdf upload received",
                extra={"document_id": document_id, "size_bytes": stored.size_bytes},
            )
            step = time.perf_counter()
            document = await self._extract(stored.path, document_id)
            extraction_ms = _elapsed_ms(step)
        # The uploaded file has been deleted; the remaining steps only use the extracted text.

        step = time.perf_counter()
        chunks = chunk_document(document, max_chars=self._limits.chunk_max_chars)
        chunking_ms = _elapsed_ms(step)
        logger.info(
            "document chunked",
            extra={
                "document_id": document_id,
                "chunk_count": len(chunks),
                "duration_ms": chunking_ms,
            },
        )

        source = Source(
            source_type="pdf",
            title=PurePath(stored.display_name).stem or "Uploaded PDF",
            filename=stored.display_name,
        )
        step = time.perf_counter()
        generated = await self._generate(
            LessonGenerationRequest(
                lesson_id=document_id, source=source, document=document, chunks=chunks
            )
        )
        generation_ms = _elapsed_ms(step)

        step = time.perf_counter()
        lesson = self._validate(generated.lesson, document_id)
        validation_ms = _elapsed_ms(step)

        record = LessonRecord(
            lesson_id=document_id,
            lesson=lesson,
            metadata=LessonMetadata(
                provider=generated.provider,
                generation_status=generated.generation_status,
                is_mock=generated.provider == "demo",
                notice=_notice_for(generated),
                model=generated.model,
                source_filename=stored.display_name,
                page_count=document.total_pages,
                chunk_count=len(chunks),
                character_count=document.character_count,
                ai_request_count=generated.ai_request_count,
                warnings=_extraction_warnings(document) + generated.warnings,
                timings=ProcessingTimings(
                    extraction_ms=extraction_ms,
                    chunking_ms=chunking_ms,
                    generation_ms=generation_ms,
                    validation_ms=validation_ms,
                    total_ms=_elapsed_ms(started),
                ),
                created_at=datetime.now(UTC),
            ),
        )
        self._store.save(record)
        logger.info(
            "lesson stored",
            extra={
                "document_id": document_id,
                "provider": generated.provider,
                "generation_status": generated.generation_status,
                "total_ms": _elapsed_ms(started),
            },
        )
        return record

    async def _extract(self, path: Path, document_id: str) -> ExtractedDocument:
        started = time.perf_counter()
        try:
            document = await asyncio.to_thread(extract_pdf, path, max_pages=self._limits.max_pages)
        except AppError as exc:
            logger.warning(
                "pdf extraction failed",
                extra={
                    "document_id": document_id,
                    "error_code": exc.code,
                    "duration_ms": _elapsed_ms(started),
                },
            )
            raise
        logger.info(
            "pdf text extracted",
            extra={
                "document_id": document_id,
                "page_count": document.total_pages,
                "character_count": document.character_count,
                "duration_ms": _elapsed_ms(started),
            },
        )
        return document

    async def _generate(self, request: LessonGenerationRequest) -> GeneratedLesson:
        started = time.perf_counter()
        try:
            generated = await self._generator.generate(request)
        except AIRateLimitError as exc:
            raise self._generation_failed(
                request,
                exc,
                ErrorCode.AI_RATE_LIMITED,
                "The AI service's free-tier limit was reached. Wait a few minutes and try again.",
            ) from exc
        except AIInvalidResponseError as exc:
            raise self._generation_failed(
                request,
                exc,
                ErrorCode.AI_INVALID_RESPONSE,
                "The AI service returned a response that could not be used. Try again.",
            ) from exc
        except AIProviderError as exc:
            raise self._generation_failed(
                request,
                exc,
                ErrorCode.AI_PROVIDER_UNAVAILABLE,
                "The AI service is not available right now. Try again later.",
            ) from exc
        except LessonAssemblyError as exc:
            raise self._generation_failed(
                request, exc, ErrorCode.LESSON_VALIDATION_FAILED, _INVALID_LESSON
            ) from exc
        logger.info(
            "lesson generated",
            extra={
                "document_id": request.lesson_id,
                "provider": generated.provider,
                "ai_requests": generated.ai_request_count,
                "warning_count": len(generated.warnings),
                "duration_ms": _elapsed_ms(started),
            },
        )
        return generated

    def _generation_failed(
        self, request: LessonGenerationRequest, exc: Exception, code: ErrorCode, message: str
    ) -> AppError:
        logger.warning(
            "lesson generation failed",
            extra={
                "document_id": request.lesson_id,
                "error_code": code,
                "reason": str(exc),
            },
        )
        return AppError(code, message)

    def _validate(self, lesson: Lesson, document_id: str) -> Lesson:
        """Validate the lesson again from its JSON form, exactly as clients will receive it."""
        started = time.perf_counter()
        try:
            validated = Lesson.model_validate(lesson.model_dump(mode="json", exclude_none=True))
        except ValidationError as exc:
            logger.warning(
                "lesson validation failed",
                extra={"document_id": document_id, "error_count": exc.error_count()},
            )
            raise AppError(ErrorCode.LESSON_VALIDATION_FAILED, _INVALID_LESSON) from exc
        logger.info(
            "lesson validated",
            extra={
                "document_id": document_id,
                "validation": "passed",
                "duration_ms": _elapsed_ms(started),
            },
        )
        return validated


def _extraction_warnings(document: ExtractedDocument) -> list[str]:
    empty_pages = document.empty_page_numbers
    if not empty_pages:
        return []
    pages = ", ".join(map(str, empty_pages))
    return [
        f"{len(empty_pages)} page(s) had no extractable text (pages {pages}). "
        "Scanned pages need OCR, which is planned."
    ]
