"""Tries each configured provider in turn, then the cache, then deterministic demo content.

    primary provider -> fallback providers -> cache -> demo

A provider is skipped when it fails in a way another provider could survive: a rate limit, an
outage, a network error, or output that did not fit the lesson format. Every provider runs the same
`AILessonGenerator`, so the draft is validated, grounded against the source pages and assembled the
same way no matter who answered. Nothing is ever presented as coming from a provider that did not
produce it: the result carries the provider that actually answered, and a warning records the
fallback.
"""

import logging

from app.ai.lesson_assembly import LessonAssemblyError
from app.ai.lesson_cache import LessonCache
from app.ai.lesson_generator import (
    AnyLessonRequest,
    GeneratedLesson,
    LessonGenerator,
    LessonProviderName,
)
from app.ai.provider import AIInputNotSupportedError, AIProviderError

logger = logging.getLogger(__name__)

# Failures that another provider might not have: quota, outage, network, unusable output.
_RECOVERABLE = (AIProviderError, LessonAssemblyError)

# What to call the material when telling the reader what they are looking at, by where it came
# from. The document wording is load-bearing for readers who have only ever uploaded a PDF.
_MATERIAL_NOUN = {"pdf": "the uploaded PDF", "video": "the uploaded video", "youtube": "this video"}
_CACHED_NOUN = {"pdf": "document", "video": "video", "youtube": "video"}


class RoutingLessonGenerator:
    def __init__(
        self,
        *,
        live: list[tuple[LessonProviderName, LessonGenerator]],
        cache: LessonCache,
        demo: LessonGenerator | None,
    ) -> None:
        self._live = live
        self._cache = cache
        self._demo = demo

    async def generate(self, request: AnyLessonRequest) -> GeneratedLesson:
        cache_key = request.cache_key
        primary = self._live[0][0] if self._live else None
        failures: list[str] = []

        for position, (provider, generator) in enumerate(self._live):
            try:
                generated = await generator.generate(request)
            except AIInputNotSupportedError:
                # Not an outage. No later provider in the chain is more likely to cope, and quietly
                # falling through to cached or demo content would hide a configuration problem
                # behind a lesson that looks fine. Stop here and let the caller report it.
                raise
            except _RECOVERABLE as exc:
                failures.append(f"{provider} ({type(exc).__name__})")
                logger.warning(
                    "provider unavailable, trying the next one",
                    extra={
                        "document_id": request.lesson_id,
                        "provider": provider,
                        "error_type": type(exc).__name__,
                    },
                )
                continue

            self._cache.put(cache_key, generated.lesson)
            status = "live" if position == 0 else "fallback"
            warnings = list(generated.warnings)
            if failures:
                warnings.insert(0, _fallback_warning(primary, provider, failures))
            logger.info(
                "lesson generated by provider",
                extra={
                    "document_id": request.lesson_id,
                    "provider": provider,
                    "generation_status": status,
                    "providers_skipped": len(failures),
                },
            )
            return GeneratedLesson(
                lesson=generated.lesson,
                warnings=warnings,
                model=generated.model,
                ai_request_count=generated.ai_request_count,
                provider=provider,
                generation_status=status,
            )

        return await self._without_live_providers(request, cache_key, failures)

    async def _without_live_providers(
        self, request: AnyLessonRequest, cache_key: str, failures: list[str]
    ) -> GeneratedLesson:
        source_type = request.source.source_type
        cached = self._cache.get(cache_key)
        if cached is not None:
            logger.info(
                "serving cached lesson",
                extra={"document_id": request.lesson_id, "provider": "cache"},
            )
            return GeneratedLesson(
                lesson=cached.model_copy(update={"id": request.lesson_id}, deep=True),
                warnings=[_cache_warning(failures, source_type)],
                provider="cache",
                generation_status="cached",
            )

        if self._demo is None:
            raise _last_failure(failures)

        logger.warning(
            "serving demo lesson", extra={"document_id": request.lesson_id, "provider": "demo"}
        )
        demo = await self._demo.generate(request)
        return GeneratedLesson(
            lesson=demo.lesson,
            warnings=[_demo_warning(failures, source_type)],
            provider="demo",
            generation_status="demo",
        )


def _fallback_warning(
    primary: LessonProviderName | None, used: LessonProviderName, failures: list[str]
) -> str:
    skipped = ", ".join(failures)
    return (
        f"{primary} was unavailable ({skipped}); this lesson was generated by {used}, "
        "not by the primary provider."
    )


def _cache_warning(failures: list[str], source_type: str) -> str:
    skipped = ", ".join(failures) or "no provider was configured"
    noun = _CACHED_NOUN.get(source_type, "material")
    return (
        f"No AI provider was available ({skipped}). This lesson was served from an earlier "
        f"successful generation of the same {noun}."
    )


def _demo_warning(failures: list[str], source_type: str) -> str:
    skipped = ", ".join(failures) or "no provider was configured"
    noun = _CACHED_NOUN.get(source_type, "material")
    material = _MATERIAL_NOUN.get(source_type, "what you sent")
    return (
        f"No AI provider was available ({skipped}) and this {noun} has no cached lesson. "
        f"This is fixed demo content and does not describe {material}."
    )


def _last_failure(failures: list[str]) -> AIProviderError:
    skipped = ", ".join(failures) or "no provider was configured"
    return AIProviderError(f"No AI provider was available ({skipped}).")
